[network]
name = "simnet"

[accounts.deployer]
mnemonic = "relax afford junior winner heart pilot range inspire dice cute cattle project"
balance = 100000000000000
derivation = "m/44'/5757'/0'/0/0"

[accounts.wallet_1]
mnemonic = "relax afford junior winner heart pilot range inspire dice cute cattle project"
balance = 100000000000000
derivation = "m/44'/5757'/0'/0/1"

[accounts.wallet_2]
mnemonic = "relax afford junior winner heart pilot range inspire dice cute cattle project"
balance = 100000000000000
derivation = "m/44'/5757'/0'/0/2"

[accounts.wallet_3]
mnemonic = "relax afford junior winner heart pilot range inspire dice cute cattle project"
balance = 100000000000000
derivation = "m/44'/5757'/0'/0/3"
