import "dotenv/config";
import fs from "node:fs";
import { broadcastTransaction, ClarityVersion, makeContractDeploy, privateKeyToAddress } from "@stacks/transactions";
const network = process.env.STACKS_NETWORK || "testnet"; if (!new Set(["testnet", "mainnet"]).has(network)) throw new Error("STACKS_NETWORK must be testnet or mainnet.");
const senderKey = process.env.STACKS_PRIVATE_KEY?.trim(); if (!senderKey) throw new Error("Missing STACKS_PRIVATE_KEY."); const feeText = process.env.STACKS_DEPLOY_FEE_MICROSTX || "300000"; if (!/^\d+$/.test(feeText) || BigInt(feeText) <= 0n) throw new Error("STACKS_DEPLOY_FEE_MICROSTX must be positive.");
const tokens = { mainnet: "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token", testnet: "ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token" }; const configured = process.env.NEXT_PUBLIC_STACKS_SBTC_CONTRACT_ID || tokens[network]; if (configured !== tokens[network]) throw new Error("sBTC identifier does not match the deployment network.");
let codeBody = fs.readFileSync("stacks/contracts/handoff-escrow.clar", "utf8"); codeBody = codeBody.replace("SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token", tokens[network]); if (!codeBody.includes(`(define-constant SBTC '${tokens[network]})`)) throw new Error("sBTC remapping did not produce the expected source.");
const transaction = await makeContractDeploy({ contractName: "handoff-escrow", codeBody, senderKey, network, fee: BigInt(feeText), clarityVersion: ClarityVersion.Clarity4 }); const response = await broadcastTransaction({ transaction, network }); const txId = response.txid || response.txId || ""; if (!txId) throw new Error(`Broadcast failed: ${JSON.stringify(response)}`); const address = privateKeyToAddress(senderKey, network);
console.log("Handoff Stacks contract submitted"); console.log("network:", network); console.log("contractId:", `${address}.handoff-escrow`); console.log("sBTC:", tokens[network]); console.log("transaction:", txId); console.log("explorer:", `https://explorer.hiro.so/txid/${txId.startsWith("0x") ? txId : `0x${txId}`}?chain=${network}`);
